<?php
function meme_menu() {
    $items['memes'] = array(
        'title' => "Chuck Memes",
        'page callback' => 'get_memes',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function get_memes() {
    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => 'http://api.icndb.com/jokes/random?firstName=Chuck&amp;lastName=Norris'
));

    $sources = curl_exec($curl);
    curl_close($curl);
    $sources = json_decode($sources, true);
    $joke=$sources['value']['joke'];

    $curl = curl_init();
    curl_setopt_array($curl, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => "http://www.splashbase.co/api/v1/images/random/",
    CURLOPT_USERAGENT => 'Codular Sample cURL Request'
));

    $sources = curl_exec($curl);
    curl_close($curl);
    $sources = json_decode($sources, true);
    $image=$sources['url'];

    global $user;
    $node = new stdClass();
    $node->title = "Chuck meme";
    $node->type = "meme";
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = $user->uid;
    $node->status = 1; //(1 or 0): published or not
    $node->promote = 1; //(1 or 0): promoted to front page
    $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write

    // Term reference (taxonomy) field
    $node->field_joke['und'][0]['value'] = $joke;
    $node->field_url['und'][0]['value'] = $image;

    $node = node_submit($node); // Prepare node for saving
    node_save($node);
    //drupal_set_message( "Node with nid " . $node->nid . " saved!\n");

    return '<img src='.$image.'> <br> <p>'.$joke.'</p>';
}
